---
title: "Making Figures for Poster"
author: "Bri Wieferich and steppe"
date: "2024-07-24"
output: html_document
---

# Import and tidy data. 

We will only use functions contained within R packages in the tidyverse ecosystem. 
The `readxl` package is part of the tidyverse ecosystem, but one of the kind of more
far flung packages which needs to be directly loaded by name rather than in the
`library(tidyverse)` call. 
```{r}
library(tidyverse)
library(readxl)
```

```{r load relevant data for plotting}
p2data <- '../data/raw/eSTZ_consistency_formatting.xlsx'
excel_sheets(p2data)
filenames <- read_excel(p2data, sheet = 'Filename schema')
maps <- read_excel(p2data, sheet = 'pdf maps formatted')
```

```{r Refine naming conventions for plotting}

filenames <- filenames |> 
  mutate(Trait = str_remove(Trait, '.*-')) |>

# We don't want to overwhelm the viewer, so we will create barplots of just 
# 3 main traits here, 'Binomial', 'Geographic_Extent', and 'Seed_Zone', 
# we will write the following text in the caption for the plots.

# "File names had three components which were only rarely present, the resolution (3 times), the Coordinate Reference System (1 time), in one instance a file contained information on two species."
  filter(Trait %in% c('Binomial', 'Geographic_Extent', 'Seed_Zone')) 
```


```{r}

# We are going to create a barplot, which we want to use to showcase the current
# disorganization of the existing file names. 

binom_plot <- filenames %>% 
  
  # when we save a plot to an object, by default Rstudio will not render it into 
  # the viewing panel (lower right, 'Plots' panel)
  filter(Trait == 'Binomial') |>
  
    # We are going to convert the character string responses to a 'factor', this
  # will allow us to easily display the values in an order, we will always put the
  # desired file name component at the bottom of the chart. 
  mutate(Response = 
           factor(Response, levels = c('scientific_name', 'NRCS_PLANTS_upper', 
                                       'NRCS_PLANTS_lower', 'common_name'))) %>% 
  
  # ggplot is low-order plotting device. it will require the following arguments: 
  # 1 data = the dataset which will be plotted, in this instance we denote that the 
  # dataset is being 'piped in' from above, and we can explicitly denote that with
  # the value '.' which means LOOK HERE in programming, and can also be seen when
  # using relative paths to load data. 
  # ggplot then uses the 'aes' or aesthetics arguments to determine HOW it will plot
  # data from the data argument. These Variable (column) names should NEVER be
  # quoted, and must be spelled exactly. 
  # within aes 'y' determines which variable will be plotted along the Y axis
  # within aes 'x' determines which variables will be plotted along the X axis 
  ggplot(., aes(y = Value, x = '', fill = forcats::fct_rev(Response))) + 
  
  # ggplot works on the notions of 'GEOMS', basically what a geom is a different 
  # type of plot. Geoms exist for nearly all common forms of data visualization 
  # if you want to learn more about the arguments  to geom_bar we can use the 
  # '?' function  to get some data on it... '?geom_bar()'
  geom_bar(position = "stack", stat = "identity") + 
  
  # labs this is a function we can use to specify labels for the plot parameters
  labs(
    x = NULL,
    y = 'Count', 
    title = 'How do filenames\nrepresent the species?', 
    fill = 'Character State'
      ) + 
  
  # ggplot has a few main default themes for styling the plot in GENERAL, e.g. 
  # whether there are hash lines on the background or not.. 
  theme_minimal() + 
  
  # we are going to label the portion of the chart, and place the legend beneath
  # rather than to the side of the plot. 
  geom_text(aes(label = Response), position = position_stack(vjust = 0.5)) +
  theme(legend.position="bottom", 
        plot.title = element_text(hjust = 0.5),
        legend.title.position = 'top', 
        legend.title = element_text(hjust = 0.5)) +

  # by default ggplot puts a lot of white space between the content of the plot
  # and the axis labels; we are going to reduce the x-axis spacing. 
  scale_x_discrete(expand = c(0,0)) +
  
  # we are also going to select some preferable colours to the default scheme
  scale_fill_manual(values = c('#C0C5C1', '#F08080', '#6279B8',  '#496F5D'))


# We will repeat the process with Geographic extent. 
extent_plot <- filenames %>% 
  filter(Trait == 'Geographic_Extent') |>
  mutate(Response = 
           factor(Response, levels = c('Specified', 'Not-specified'))) %>% 
  ggplot(., aes(y = Value, x = '', fill = forcats::fct_rev(Response))) + 
  geom_bar(position = "stack", stat = "identity") + 
  labs(y = 'Count', x = NULL, title = 'Is the geographic\nextent specified?', 
       fill = 'Specified') +
  theme_minimal() +
  theme(
    legend.position="bottom", 
    plot.title = element_text(hjust = 0.5),
    legend.title.position = 'top', 
    legend.title = element_text(hjust = 0.5)
    ) + 
  scale_x_discrete(expand = c(0,0)) +
  
  geom_text(aes(label = Response), position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = c('#C0C5C1',  '#496F5D')) 


file_plot <- filenames %>% 
  filter(Trait == 'Seed_Zone') |>
  mutate(Response = 
           factor(Response, levels = c('zone', 'seed_zone', 'sz', 'missing'))) %>% 
  ggplot(., aes(y = Value, x = '', fill = forcats::fct_rev(Response))) + 
  geom_bar(position = "stack", stat = "identity", width=1) + 
  labs(y = 'Count', x = NULL, title = 'Do files mention\nthey contain STZs?', 
       fill = 'Seed Zone Specified') + 
    scale_fill_manual(values = c('#C0C5C1', '#F08080', '#6279B8',  '#496F5D'))+
  theme_minimal() +
  theme(
    legend.position="bottom", 
    plot.title = element_text(hjust = 0.5),
    legend.title.position = 'top', 
    legend.title = element_text(hjust = 0.5)
    ) + 
  scale_x_discrete(expand = c(0,0)) +
  geom_text(aes(label = Response), position = position_stack(vjust = 0.5)) 


fnames <- binom_plot  + file_plot + extent_plot
ggsave('../poster/filenames.png', fnames, width = 10, height = 10, units = 'in')

rm(binom_plot, file_plot, extent_plot)
```


Maps

```{r}

```

